config/routes.rb
Rails.application.routes.draw do
  	mount_devise_token_auth_for 'Userapi', at: 'auth'
	resources :cad_produtos
	devise_for :users
	get 'home/index'
	post 'home/index'
	root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cad_produto.rb
class CadProduto < ApplicationRecord
  has_attached_file :imagem, styles: { large: "600x600", medium: "300x300>", thumb: "150x150>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/

  acts_as_paranoid
  belongs_to :user

  def self.to_csv
  	CSV.generate do |csv|
  		csv << column_names
  		all.each do |cad_produto|
  			csv << cad_produto.attributes.values_at(*column_names)
  		end
  	end
  end
end

app/models/cadastro_prod.rb
class CadastroProd < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	acts_as_paranoid
	has_many :cad_produtos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/userapi.rb
# frozen_string_literal: true

class Userapi < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  include DeviseTokenAuth::Concerns::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :null_session
	skip_before_action :verify_authenticity_token, if: -> {params[:controller].split('/')[0] == 'devise_token_auth'}
end

app/controllers/cad_produtos_controller.rb
class CadProdutosController < ApplicationController
  before_action :set_cad_produto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /cad_produtos
  # GET /cad_produtos.json
  def index
    @cad_produtos = current_user.cad_produtos.order(:id)
    respond_to do |format|
      format.html
      format.csv { send_data @cad_produtos.to_csv, filename: "Produtos-#{Date.today}.csv"}
    end
  end

  # GET /cad_produtos/1
  # GET /cad_produtos/1.json
  def show
  end

  # GET /cad_produtos/new
  def new
    @cad_produto = CadProduto.new
  end

  # GET /cad_produtos/1/edit
  def edit
  end

  # POST /cad_produtos
  # POST /cad_produtos.json
  def create
    @cad_produto = CadProduto.new(cad_produto_params)
    @cad_produto.user_id = current_user.id
    respond_to do |format|
      if @cad_produto.save
        format.html { redirect_to @cad_produto, notice: 'Cad produto was successfully created.' }
        format.json { render :show, status: :created, location: @cad_produto }
      else
        format.html { render :new }
        format.json { render json: @cad_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cad_produtos/1
  # PATCH/PUT /cad_produtos/1.json
  def update
    respond_to do |format|
      if @cad_produto.update(cad_produto_params)
        format.html { redirect_to @cad_produto, notice: 'Cad produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @cad_produto }
      else
        format.html { render :edit }
        format.json { render json: @cad_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cad_produtos/1
  # DELETE /cad_produtos/1.json
  def destroy
    @cad_produto.destroy
    respond_to do |format|
      format.html { redirect_to cad_produtos_url, notice: 'Cad produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cad_produto
      @cad_produto = CadProduto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cad_produto_params
      params.require(:cad_produto).permit(:categoria, :produto, :caracteristica, :user_id, :imagem)
    end
end

app/controllers/cadastro_prods_controller.rb
class CadastroProdsController < ApplicationController
  before_action :set_cadastro_prod, only: [:show, :edit, :update, :destroy]

  # GET /cadastro_prods
  # GET /cadastro_prods.json
  def index
    @cadastro_prods = CadastroProd.all
  end

  # GET /cadastro_prods/1
  # GET /cadastro_prods/1.json
  def show
  end

  # GET /cadastro_prods/new
  def new
    @cadastro_prod = CadastroProd.new
  end

  # GET /cadastro_prods/1/edit
  def edit
  end

  # POST /cadastro_prods
  # POST /cadastro_prods.json
  def create
    @cadastro_prod = CadastroProd.new(cadastro_prod_params)

    respond_to do |format|
      if @cadastro_prod.save
        format.html { redirect_to @cadastro_prod, notice: 'Cadastro prod was successfully created.' }
        format.json { render :show, status: :created, location: @cadastro_prod }
      else
        format.html { render :new }
        format.json { render json: @cadastro_prod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastro_prods/1
  # PATCH/PUT /cadastro_prods/1.json
  def update
    respond_to do |format|
      if @cadastro_prod.update(cadastro_prod_params)
        format.html { redirect_to @cadastro_prod, notice: 'Cadastro prod was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadastro_prod }
      else
        format.html { render :edit }
        format.json { render json: @cadastro_prod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastro_prods/1
  # DELETE /cadastro_prods/1.json
  def destroy
    @cadastro_prod.destroy
    respond_to do |format|
      format.html { redirect_to cadastro_prods_url, notice: 'Cadastro prod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro_prod
      @cadastro_prod = CadastroProd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_prod_params
      params.require(:cadastro_prod).permit(:categoria, :produto, :preco, :info)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cad_produtos_helper.rb
module CadProdutosHelper
end

app/helpers/cadastro_prods_helper.rb
module CadastroProdsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cad_produtos/_form.html.erb
<%= form_with(model: @cad_produto, html: { multipart: true }, local: true) do |form| %>
  <% if @cad_produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cad_produto.errors.count, "error") %> prohibited this @cad_produto from being saved:</h2>

      <ul>
      <% @cad_produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :categoria, class: "w3-text-blue"%>
    <%= form.text_field :categoria, class: "w3-border w3-light-grey" %>
  </div>

  <div class="field">
    <%= form.label :produto, class: "w3-text-blue" %>
    <%= form.text_field :produto, class: "w3-border w3-light-grey" %>
  </div>

  <div class="field">
    <%= form.label :caracteristica, class: "w3-text-blue" %>
    <%= form.text_area :caracteristica, class: "w3-border w3-light-grey" %>
  </div>

  <div class="field">
    <%= form.label :imagem, class: "w3-text-blue" %>
    <%= form.file_field :imagem, class: "w3-btn w3-white"%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cad_produtos/edit.html.erb
<div class="w3-container w3-display-middle w3-center w3-border" style="width:25%">
  <div class="w3-container w3-blue">
  <h2>Editar Produto</h2>
  </div>

<%= render 'form', cad_produto: @cad_produto %>

<%= link_to 'Mostrar', @cad_produto %> |
<%= link_to 'Voltar', cad_produtos_path %> |
<%= link_to 'Descartar', @cad_produto, method: :delete, data: {confirm:'Are you sure?'} %>

app/views/cad_produtos/index.html.erb
<!DOCTYPE html>
<html>
<title>Cadastrar</title>

<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

  <header class="w3-container w3-blue w3-center " style="padding:50px 16px">
    <h1 class="w3-margin w3-jumbo">Cadastrar</h1>
    <a href="cad_produtos/new"><button class="w3-btn w3-black w3-padding-large w3-large w3-margin-top">Novo Produto</button></a>
  </header>

<!DOCTYPE html>
<html>
<head>
<style>
#customers {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

#customers td, #customers th {
    border: 1px solid #ddd;
    padding: 8px;
}


#customers th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #0b82dd;
    color: white;
}
</style>
</head>
<body>

<table id="customers">
    <thead>
    <tr>
      <th>Categoria</th>
      <th>Produto</th>
      <th>Caracteristica</th>
      <th>Imagem</th>
      <th colspan="2">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @cad_produtos.each do |cad_produto| %>
      <tr>
        <td><%= cad_produto.categoria %></td>
        <td><%= cad_produto.produto %></td>
        <td><%= cad_produto.caracteristica %></td>
        <td align="center"><%= image_tag cad_produto.imagem.url(:medium) %></td>
        <td><%= link_to 'Expandir', cad_produto %></td>
        <td><%= link_to 'Editar', edit_cad_produto_path(cad_produto) %></td>
      </tr>
    <% end %>
      <tr>
        <td align="center" colspan="6"><%= link_to "Download CSV", cad_produtos_path(format: "csv") %></td>
      </tr>
  </tbody>
</table>


</body>
</html>

app/views/cad_produtos/new.html.erb
<div class="w3-container w3-display-middle w3-center w3-border" style="width:25%">
  <div class="w3-container w3-blue">
  <h2>Novo Produto</h2>
  </div>
 
<%= render :partial => 'form' %>

<%= link_to 'Voltar', cad_produtos_path %>

app/views/cad_produtos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="w3-container w3-display-middle w3-center w3-border" style="width:25%">
  <div class="w3-container w3-blue">
  <h2>Descrição Completa</h2>
  </div>

<p>
  <strong>Categoria:</strong>
  <%= @cad_produto.categoria %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @cad_produto.produto %>
</p>

<p>
  <strong>Caracteristica:</strong>
  <%= @cad_produto.caracteristica %>
</p>

<p>
  <strong>User:</strong>
  <%= @cad_produto.user.email %>
</p>

<p>
	<strong>Imagem:</strong><br />
	<%= image_tag @cad_produto.imagem.url(:medium) %>
</p>


<%= link_to 'Editar', edit_cad_produto_path(@cad_produto) %> |
<%= link_to 'Voltar', cad_produtos_path %>

app/views/cadastro_prods/_form.html.erb
<%= form_with(model: cadastro_prod, local: true) do |form| %>
  <% if cadastro_prod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cadastro_prod.errors.count, "error") %> prohibited this cadastro_prod from being saved:</h2>

      <ul>
      <% cadastro_prod.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.text_field :categoria %>
  </div>

  <div class="field">
    <%= form.label :produto %>
    <%= form.text_field :produto %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_area :info %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cadastro_prods/edit.html.erb
<h1>Editing Cadastro Prod</h1>

<%= render 'form', cadastro_prod: @cadastro_prod %>

<%= link_to 'Show', @cadastro_prod %> |
<%= link_to 'Back', cadastro_prods_path %>

app/views/cadastro_prods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cadastro Prods</h1>

<table>
  <thead>
    <tr>
      <th>Categoria</th>
      <th>Produto</th>
      <th>Preco</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cadastro_prods.each do |cadastro_prod| %>
      <tr>
        <td><%= cadastro_prod.categoria %></td>
        <td><%= cadastro_prod.produto %></td>
        <td><%= cadastro_prod.preco %></td>
        <td><%= cadastro_prod.info %></td>
        <td><%= link_to 'Show', cadastro_prod %></td>
        <td><%= link_to 'Edit', edit_cadastro_prod_path(cadastro_prod) %></td>
        <td><%= link_to 'Destroy', cadastro_prod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cadastro Prod', new_cadastro_prod_path %>

app/views/cadastro_prods/new.html.erb
<h1>New Cadastro Prod</h1>

<%= render 'form', cadastro_prod: @cadastro_prod %>

<%= link_to 'Back', cadastro_prods_path %>

app/views/cadastro_prods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Categoria:</strong>
  <%= @cadastro_prod.categoria %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @cadastro_prod.produto %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @cadastro_prod.preco %>
</p>

<p>
  <strong>Info:</strong>
  <%= @cadastro_prod.info %>
</p>

<%= link_to 'Edit', edit_cadastro_prod_path(@cadastro_prod) %> |
<%= link_to 'Back', cadastro_prods_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<title>K-dastra</title>

<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<!-- Header -->
  <header class="w3-container w3-blue w3-center" style="padding:50px 16px">
    <h1 class="w3-margin w3-jumbo">K-dastra</h1>
    <a href="cad_produtos"><button class="w3-btn w3-black w3-padding-large w3-large w3-margin-top">Mostrar Produtos</button></a>
  </header>

  <!-- First Grid -->
  <div class="w3-row-padding w3-padding-64 w3-container">
    <div class="w3-content">
      <div class="w3-twothird">
        <h1>Sobre a aplicação</h1>
        <h5 class="w3-padding-32">Aplicação web capaz de cadastrar seus produtos, com suas respectivas imagens, e oferecer um documento (.csv), para download, dos produtos cadastrados de forma organizada.</h5>

        <p class="w3-text-grey">Projeto desenvolvido em Ruby on Rails durante o processo seletivo para vaga de estagiário na empresa Tracking Trade.</p>
      </div>
    </div>
  </div>

  <div class="w3-container w3-blue w3-center w3-opacity w3-padding-50">
      <h1 class="w3-margin w3-medium">Aceite o que não pode mudar. <br>Mude o que não pode aceitar.<br>- Prof. Galvão</h1>
  </div>

  <!-- Footer -->
  <footer class="w3-container w3-padding-64 w3-center w3-opacity">  
    <div class="w3-xlarge w3-padding-32">
      <a href="https://github.com/Jcns"><i class="fa fa-github w3-hover-opacity"></a></i>
      <a href="https://www.facebook.com/jeancarlosnsilva"><i class="fa fa-facebook w3-hover-opacity"></a></i> 
    </div>
    <p>Developed by <a href="https://github.com/Jcns/K-dastra" target="_blank">Jean Silva</a></p>
    <p>Powered by <a href="https://www.w3schools.com/" target="_blank">W3Schools</a></p>

  </footer>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>K-dastra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
    .w3-bar,h1,button {font-family: "Montserrat", sans-serif}
    </style>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="w3-top">

      <div class="w3-bar w3-blue w3-card w3-right w3-medium">
        <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-small w3-hover-white w3-large w3-red" href="
        javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
        <%= link_to "Página inicial", root_path, class: "w3-bar-item w3-button w3-left w3-padding-large w3-hover-white" %>
        <% if signed_in? %>
          <%= link_to 'Sair', destroy_user_session_path, method: :delete, data: {confirm:"Deseja mesmo sair?"}, class: "w3-bar-item w3-button w3-padding-large w3-green w3-right"%>
          <%= link_to "Cadastrar Produtos", new_cad_produto_path, class: "w3-bar-item w3-button w3-padding-large w3-green w3-right"%>
          <div class="w3-bar-item w3-padding-large w3-green w3-right">
           Bem-vindo: <%= current_user.email%>
          </div>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "w3-bar-item w3-button w3-padding-large w3-green w3-right"%>
          <%= link_to "Cadastre-se", new_user_registration_path, class: "w3-bar-item w3-button w3-padding-large w3-green w3-right" %>
        <% end %>               
      </div>

    </div>
    <%= yield %>
  <script>
  // Used to toggle the menu on small screens when clicking on the menu button
  function myFunction() {
      var x = document.getElementById("navDemo");
        if (x.className.indexOf("w3-show") == -1) {
            x.className += " w3-show";
        } else { 
            x.className = x.className.replace(" w3-show", "");
          }
        }
  </script>
  </body>
</html>